version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    restart: always
    volumes:
      - /tmp/kafka-logs:/kafka/kafka-logs # optional

  producer:
    build: ./producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    command: ["/wait-for-it.sh", "kafka:9092", "--", "python", "producer.py"]
    restart: always

  consumer:
    build: ./consumer
    depends_on:
      - kafka
    volumes:
      - ./consumer/logs:/app/logs  # Mount logs to host
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    command: ["/wait-for-it.sh", "kafka:9092", "--", "python", "consumer.py"]
    restart: always
